// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9misSz-kgaTT-dqBp03FZjNtpuGmxp0',
    appId: '1:751971356662:web:4b96b309088506ca5141d7',
    messagingSenderId: '751971356662',
    projectId: 'purseonality-48dc2',
    authDomain: 'purseonality-48dc2.firebaseapp.com',
    storageBucket: 'purseonality-48dc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhYuyk2FD2sxeFja4GylJducBcM7v2E8',
    appId: '1:751971356662:android:b940ac5d0b332ee75141d7',
    messagingSenderId: '751971356662',
    projectId: 'purseonality-48dc2',
    storageBucket: 'purseonality-48dc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBo2bkPMfbWdRev8YVxQgS8dfw2bq6vM',
    appId: '1:751971356662:ios:e9d5a2812b725d505141d7',
    messagingSenderId: '751971356662',
    projectId: 'purseonality-48dc2',
    storageBucket: 'purseonality-48dc2.firebasestorage.app',
    iosBundleId: 'com.example.purseonality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmBo2bkPMfbWdRev8YVxQgS8dfw2bq6vM',
    appId: '1:751971356662:ios:e9d5a2812b725d505141d7',
    messagingSenderId: '751971356662',
    projectId: 'purseonality-48dc2',
    storageBucket: 'purseonality-48dc2.firebasestorage.app',
    iosBundleId: 'com.example.purseonality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT9misSz-kgaTT-dqBp03FZjNtpuGmxp0',
    appId: '1:751971356662:web:3582dc0cab9cc9245141d7',
    messagingSenderId: '751971356662',
    projectId: 'purseonality-48dc2',
    authDomain: 'purseonality-48dc2.firebaseapp.com',
    storageBucket: 'purseonality-48dc2.firebasestorage.app',
  );
}
